<?php
defined('ERROR_MESSAGE_SYSBUSY') or define('ERROR_MESSAGE_SYSBUSY', '0100001009');//系统繁忙请重试
defined('ERRORCODE_MISS_ARGUMENT') or define('ERRORCODE_MISS_ARGUMENT', '0100001010');//参数不完整
//自定义错误
defined('ERRORCODE_ERROR_PARAM') or define('ERRORCODE_ERROR_PARAM', '0211011000');//参数错误
defined('ERRORCODE_ERROR_TOKEN') or define('ERRORCODE_ERROR_TOKEN', '0211011001');//token验证失败
defined('ERRORCODE_AUTHORIZE_FAIL') or define('ERRORCODE_AUTHORIZE_FAIL', '0211011002');//授权失败
defined('ERRORCODE_GETINFO_FAIL') or define('ERRORCODE_GETINFO_FAIL', '0211011003');//授权失败
defined('ERRORCODE_ERROR_RELOGIN') or define('ERRORCODE_ERROR_RELOGIN', '0211011004');//请重新登录
defined('ERRORCODE_CINEMA_SYSTEM_EXCEPTION') or define('ERRORCODE_CINEMA_SYSTEM_EXCEPTION', '0211012014');//影院售票系统异常，请稍后再试
defined('ERRORCODE_REG_USER_FAILED') or define('ERRORCODE_REG_USER_FAILED', '0211011005');//注册用户失败
defined('ERRORCODE_DECRYPT_OPENID') or define('ERRORCODE_DECRYPT_OPENID', '0211011006');//解密openid失败
defined('ERRORCODE_ORDERID_CANT_NULL') or define('ERRORCODE_ORDERID_CANT_NULL', '0211011007');//订单号不能为空
defined('ERRORCODE_MOBILE_CANT_NULL') or define('ERRORCODE_MOBILE_CANT_NULL', '0211011008');//手机号不能为空

//用户中心
defined('ERRORCODE_USER_CENTER_PARAMS_ERROR') or define('ERRORCODE_USER_CENTER_PARAMS_ERROR', '0211021000');//参数错误
defined('ERRORCODE_USER_CENTER_UID_ERROR') or define('ERRORCODE_USER_CENTER_UID_ERROR', '0211021001');      //无效的uid
defined('ERRORCODE_USER_WECHAT_INFO_ERROR') or define('ERRORCODE_USER_WECHAT_INFO_ERROR', '0211021002');      //获取用户微信信息失败
defined('ERRORCODE_USER_CENTER_INFO_REGISTER_ERROR') or define('ERRORCODE_USER_CENTER_INFO_REGISTER_ERROR', '0211021003'); //注册用户失败
defined('ERRORCODE_BIND_BONUS_RES_ERROR') or define('ERRORCODE_BIND_BONUS_RES_ERROR', '0211021004');//红包资源不存在
defined('ERRORCODE_USER_CENTER_MISS_OPENID_ERROR') or define('ERRORCODE_USER_CENTER_MISS_OPENID_ERROR', '0211021005'); //缺少openId参数
defined('ERRORCODE_USER_MISSS_UNIONID_ERROR') or define('ERRORCODE_USER_MISSS_UNIONID_ERROR', '0211021006'); //unionId不能为空
defined('ERRORCODE_USER_GET_ACCESSTOKEN_ERROR') or define('ERRORCODE_USER_GET_ACCESSTOKEN_ERROR', '0211021007'); //accesstoken获取失败

defined('ERRORCODE_USER_CENTER_MISS_OPENID_ERROR') or define('ERRORCODE_USER_CENTER_MISS_OPENID_ERROR', '0211021005'); //缺少openId参数

//商品中心
defined('ERRORCODE_GOOD_CENTER_PARAMS_ERROR') or define('ERRORCODE_GOOD_CENTER_PARAMS_ERROR', '0211031000');//参数错误

//营销中心
defined('ERRORCODE_GOOD_BONUS_EXCHANGE_PARAMS_ERROR') or define('ERRORCODE_GOOD_BONUS_EXCHANGE_PARAMS_ERROR', '0211041000');//参数错误
defined('ERRORCODE_POINT_CARD_PARAMS_ERROR') or define('ERRORCODE_POINT_CARD_PARAMS_ERROR', '0211041001');//点卡参数错误
//明星问候
defined('ERRORCODE_NOT_EXISTS_GREETING') or define('ERRORCODE_NOT_EXISTS_GREETING', '0210181001');//问候不存在
//订单中心
defined('ERRORCODE_ORDER_CENTER_PARAMS_ERROR') or define('ERRORCODE_ORDER_CENTER_PARAMS_ERROR', '0211051000');//参数错误

//短信相关
defined('ERRORCODE_SMS_PARAMS_SLIDE_ERROR') or define('ERRORCODE_SMS_PARAMS_SLIDE_ERROR', '0211061000');//参数错误-缺少滑动认证信息
defined('ERRORCODE_SMS_PARAMS_PHONE_ERROR') or define('ERRORCODE_SMS_PARAMS_PHONE_ERROR', '0211061001');//参数错误-缺少手机号信息
defined('ERRORCODE_SMS_SEND_ERROR') or define('ERRORCODE_SMS_SEND_ERROR', '0211061002');//短信发送失败
defined('ERRORCODE_SMS_SLIDE_CHECK_ERROR') or define('ERRORCODE_SMS_SLIDE_CHECK_ERROR', '0211061003');//滑动验证失败
defined('ERRORCODE_SMS_PARAMS_PHONE_CODE_ERROR') or define('ERRORCODE_SMS_PARAMS_PHONE_CODE_ERROR', '0211061004');//手机号验证时,手机号或短信码参数不全
defined('ERRORCODE_SMS_VALID_ERROR') or define('ERRORCODE_SMS_VALID_ERROR', '0211061005');//手机号验证时,手机号或短信码参数不全

//大数据相关
defined('ERRORCODE_BIG_DATA_PARAMS_ERROR') or define('ERRORCODE_BIG_DATA_PARAMS_ERROR', '0211071000');//手机号验证时,手机号或短信码参数不全

//影院收藏
defined('ERRORCODE_CINEMA_FAVORITE_PARAMS_ERROR') or define('ERRORCODE_CINEMA_FAVORITE_PARAMS_ERROR', '0211081000');//参数错误
defined('ERRORCODE_CINEMA_FAVORITE_FAILURE') or define('ERRORCODE_CINEMA_FAVORITE_FAILURE', '0211081001');//收藏失败
defined('ERRORCODE_CINEMA_UN_FAVORITE_FAILURE') or define('ERRORCODE_CINEMA_UN_FAVORITE_FAILURE', '0211081002');//取消收藏失败

//观影秘籍相关
defined('ERRORCODE_MOVIE_GUIDE_PARAMS_ERROR') or define('ERRORCODE_MOVIE_GUIDE_PARAMS_ERROR', '0211091000');//参数错误


//APP版本信息
defined('ERRORCODE_APP_VERSION_NOT_EXIST_ERROR') or define('ERRORCODE_APP_VERSION_NOT_EXIST_ERROR', '-11251001');//参数错误
defined('ERRORCODE_VERIFY_CODE_FAIL') or define('ERRORCODE_VERIFY_CODE_FAIL', '-191007');//参数错误
defined('ERRORCODE_BIND_BONUS_RES_ERROR') or define('ERRORCODE_BIND_BONUS_RES_ERROR', '0211021004');//红包资源不存在

//观影轨迹相关
defined('ERRORCODE_USER_TRACE_PARAMS_ERROR') or define('ERRORCODE_USER_TRACE_PARAMS_ERROR', '0211101000');//参数错误
defined('ERRORCODE_DELETE_USER_TRACE_PATH_ERROR') or define('ERRORCODE_DELETE_USER_TRACE_PATH_ERROR', '0211101001');//删除观影轨迹失败


//手Q观影社区
defined('ERRORCODE_FRIENDS_WATCH_PARAMS_ERROR') or define('ERRORCODE_FRIENDS_WATCH_PARAMS_ERROR', '0210191000');//参数缺少
defined('ERRORCODE_FRIENDS_WATCH_FAIL_ACCESSTOKEN_ERROR') or define('ERRORCODE_FRIENDS_WATCH_FAIL_ACCESSTOKEN_ERROR', '0210191001');//accesstoken未获取到
